# ------------------------------------------------------------------------------
# ARGOCD PROJECT CONFIGS
# ------------------------------------------------------------------------------
configs:

  # NAMESPACES to be used
  namespaces:
#    - ingress-nginx
#    - monitoring
#    - testing

# ------------------------------------------------------------------------------
# APPLICATIONS
# ------------------------------------------------------------------------------
applications:
# ------------------------------------------------------------------------------
  - name: argo-cd
    namespace: argocd
    additionalLabels: { }
    additionalAnnotations:
      argocd.argoproj.io/sync-wave: "1"

    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: argoenv
    source:
      repoURL: https://github.com/TheAutomationRules/helm.git
      targetRevision: main
      path: charts/argo-cd/5.51.6
      helm:
        valueFiles:
          - values-custom.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      syncOptions:
        - Validate=false
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
    info:
      - name: url
        value: https://github.com/TheAutomationRules/helm/blob/main/README.md
  # ------------------------------------------------------------------------------
  - name: argo-workflows
    namespace: argocd
    additionalLabels: { }
    additionalAnnotations:
      argocd.argoproj.io/sync-wave: "2"

    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: argoenv
    source:
      repoURL: https://github.com/TheAutomationRules/helm.git
      targetRevision: main
      path: charts/argo-workflows/0.33.3
      helm:
        valueFiles:
          - values-custom.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: argo
    syncPolicy:
      syncOptions:
        - Validate=false
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
    info:
      - name: url
        value: https://github.com/TheAutomationRules/helm/blob/main/README.md
  # ------------------------------------------------------------------------------
  - name: minio
    namespace: argocd
    additionalLabels: { }
    additionalAnnotations:
      argocd.argoproj.io/sync-wave: "3"

    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: argoenv
    source:
      repoURL: https://github.com/TheAutomationRules/helm.git
      targetRevision: main
      path: charts/minio/8.0.10
      helm:
        valueFiles:
          - values-custom.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      syncOptions:
        - Validate=false
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
    info:
      - name: url
        value: https://github.com/TheAutomationRules/helm/blob/main/README.md
  # ------------------------------------------------------------------------------